### PR TITLE
no shell for subprocess call

### PR DESCRIPTION
**Pull request by weiyuan-jiang**
remove shell = True from subprocess call according to Python's recommendation

Motivated by some users' reports about ldas_setup crashing in GEOSldas v17.10.0 because of environment conflicts.

### CODE REVIEW

**Review by gmao-rreichle — APPROVED** [review]
Provisionally approving PR pending report of successful testing.
@weiyuan-jiang, @biljanaorescanin:  Please report successful testing on the PR (and coordinate who will be testing if tests haven't been completed already), then go ahead and merge.

**Comment by mathomp4** [comment]
A suggestion. If any of the commands you are operating on might have paths with spaces, I recommend changing:
```python
sp.call(cmd.split())
```
to be:
```python
import shlex
sp.call(shlex.split(cmd))
```

A user of `mepo` had the model in a directory tree with spaces in the name and [a PR was born](https://github.com/GEOS-ESM/mepo/pull/191).

Now, if there are no paths in any of the commands, then this is moot.

**Comment by gmao-rreichle** [comment]
Thanks, @mathomp4, for the helpful hint.   It sounds like we should do this even if there aren't paths in our commands at this time.  If there aren't paths now, there may well be later.

**Comment by weiyuan-jiang** [comment]
> ```python
> shlex.split(cmd)
> ```

That is a good point. Changed

**Review by gmao-rreichle — APPROVED** [review]
Provisionally re-approving PR pending report of successful testing.
**@weiyuan-jiang, @biljanaorescanin: Please report successful testing on the PR if tests have been done (or coordinate who will be testing if tests haven't been completed already), then go ahead and merge.**

**Comment by biljanaorescanin** [comment]
All Nightly tests passed.

**Pull request merged**
