### PR TITLE
restart hour is passed to mk_GEOSldasRestart

### PR DESCRIPTION
**Pull request by weiyuan-jiang**

### CODE REVIEW

**Comment by gmao-jkolassa** [comment]
Hi @weiyuan-jiang , quick question, the components.yaml file for this branch is currently pointing at GEOSgcm_GridComp branch feature/jkolassa_cnclm45. For testing, should this point at feature/wjiang/jkolassa_cnclm45_hour?

**Comment by weiyuan-jiang** [comment]
@gmao-jkolassa , Yes. those components should stay together. After your fresh clone, change components.yaml and build.

**Comment by gmao-jkolassa** [comment]
@weiyuan-jiang , I set up an offline GEOSldas experiment with restart option 1 and that generated the restarts correctly. The experiment is now running and I will assess the science output as soon as it is done.

I also tried setting up an experiment with restart option 2, but that failed during ldas_setup. The error message is 
`cmd:   ./process_rst.csh  g0620  GEOSldas_CN45  /discover/nobackup/jkolassa/regrid_test_2  /discover/nobackup/elee15/GEOSldas_4_5/bcs_M36/Icarus-NLv3/Icarus-NLv3_EASE/SMAP_EASEv2_M36/  SMAP_EASEv2_M36_964x406.til  catchcnclm45  2  19800101_00  clm4.5_DE720  global  /discover/nobackup/jkolassa/clm4.5_restart/  1  0  50.0  13  13`
 
`Submitted batch job 45266056
Please hold on for a while until the restart file is created  .....
|restart: 2
catchRstFile: /discover/nobackup/jkolassa/regrid_test_2/GEOSldas_CN45/mk_restarts/catchcnclm45_internal_rst.19800101
catchRstFile: 
Traceback (most recent call last):
  File "./ldas_setup", line 1642, in <module>
    status = ld.createLnRstBc()
  File "./ldas_setup", line 885, in createLnRstBc
    os.symlink(catchRstFile, myCatchRst)
OSError: [Errno 2] No such file or directory`

I checked the mk_restarts directory and the file there is called 'catchcn_internal_rst.19800101'.

The experiment is in /discover/nobackup/jkolassa/regrid_test_2/GEOSldas_CN45/ and the build is in /discover/nobackup/jkolassa/regrid_test_2/GEOSldas/.

The restart files are in /discover/nobackup/jkolassa/clm4.5_restart

**Comment by weiyuan-jiang** [comment]
@gmao-jkolassa , I have fixed some bugs. Would you please try again?

**Comment by gmao-rreichle** [comment]
> I checked the mk_restarts directory and the file there is called 'catchcn_internal_rst.19800101'.

Just curious, why does the restart file name not include hour and minute?  Might this be the issue?

**Comment by weiyuan-jiang** [comment]
That is an interim name. It is not important as long as it is consistent.

**Comment by gmao-jkolassa** [comment]
@weiyuan-jiang , with the updates you made ldas_setup now completes successfully for restart option 2. The simulation is running now and I will assess the science results when it is done.

**Comment by gmao-jkolassa** [comment]
@weiyuan-jiang , I validated the science results from the two experiments. The experiment using restart option 2 looks good. But for the experiment with restart option 1 it seems that the (LDASsa) restart file I am using was not 'reordered' correctly. The experiment is in /discover/nobackup/jkolassa/regrid_test_2/GEOSldas_CN40.

The last time we encountered this issue, you made changes in GEOSldas branch `feature/wjiang/jkolassa_cnclm45_mk_restarts` and GEOSgcm_GridComp branch `feature/wjiang/jkolassa_cnclm45_mk_restart`, which I merged into branch `feature/jkolassa_cnclm45 `for both repositories. Do the current branches (`feature/wjiang/jkolassa_cnclm45_hour` for both repositories) include these changes?

**Comment by gmao-jkolassa** [comment]
@weiyuan-jiang , my bad! I thought the recent commits only affected restart option 2. I will re-run the restart option 1 experiment with the latest code, but I will wait until you have pushed the changes to GMAO_Shared.

**Comment by weiyuan-jiang** [comment]
@gmao-jkolassa  I have updated GMAO_share which will find LDASsa's restart name.  It needs "catchcnclmxx" in it though ( you did it right in your folder). So please remove those names with "internal_rst" if it is LDASsa restart.

**Comment by weiyuan-jiang** [comment]
Another side question. It seems there is no way going back to LDASsa after restart is reordered

**Comment by gmao-jkolassa** [comment]
> Another side question. It seems there is no way going back to LDASsa after restart is reordered

Do you mean to produce outputs or restarts in the LDASsa order?

**Comment by gmao-jkolassa** [comment]
@weiyuan-jiang I repeated my offline experiments with your recent changes to GMAO_Shared. The science results now look good for both the experiment with restart option 1 and the experiment with restart option 2.

I will now test the latest changes in coupled (AGCM) simulations and will report back once I have the results from those.

**Comment by weiyuan-jiang** [comment]
@gmao-jkolassa , Since you have tested , I will merge three PRs. ( this one + https://github.com/GEOS-ESM/GMAO_Shared/pull/204 + https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/449

**Pull request merged**
