### PR TITLE
add SLES 12 support and compress land pert restart

### PR DESCRIPTION
**Pull request by weiyuan-jiang**
#123 #112 #110 #109 issues are addressed in this pull request

### CODE REVIEW

**Comment by gmao-rreichle** [comment]
@mathomp4 : This pull request would use v2.0.1 of ESMA_env, which points to the Intel 18 compiler, which works for us but produces an error message.
@weiyuan-jiang is telling me that you are about to issue a new release of ESMA_env that would move to Intel 19 or 20 and thereby fix the issue with the error message.
Should we wait for you to do that, and then update the pull request accordingly?  
We do need to create a new GEOSldas tag this week at the very latest.

**Comment by mathomp4** [comment]
@gmao-rreichle I'm currently testing new `g5_modules` setups. I had thought about moving to Intel Compiler 20 with Intel MPI 20, but that is a non-zero-diff change. But I asked NCCS to allow Intel Compiler 18 with the later Intel MPI versions. They fixed up lmod and I'm currently building an Intel 18.0.5 + Intel MPI 19.1 Baselibs. Hopefully this will allow SLES11 and SLES12 versions of GEOSgcm (and ldas?) to be zero-diff between the two machines.

**Comment by gmao-rreichle** [comment]
@mathomp4 : I think @weiyuan-jiang tested Intel Compiler 20 (presumably with Intel MPI 20) and found it to be zero-diff for GEOSldas.  So I assume that whatever you get to work for the GCM should also work for GEOSldas.  Please keep us posted.

**Comment by mathomp4** [comment]
@gmao-rreichle My guess is that the non-zero-diff ness of the GEOSgcm comes from the vectorization we turn on in FV3. The rest of the model is compiled pretty safely (precise math) so it's rare to have a compiler-induced difference. But not impossible...

I'm currently building GEOSgcm and will test soon. If it works, I'll pass on a `g5_modules` for @weiyuan-jiang to try.

**Comment by mathomp4** [comment]
Okay. I think a combination of Intel Compiler 18 and Intel MPI 19.1 seems to work in my testing. Before I commit it to ESMA_env, I've asked @weiyuan-jiang (on Skype, but we can track it here too) to test:
```
/gpfsm/dswdev/mathomp4/Models/GEOSgcm-stock-SLES11_and_12/GEOSgcm/@env/g5_modules
```
with the LDAS. If that works, I'll make a new release.

**Comment by mathomp4** [comment]
@weiyuan-jiang said that my new modules setup works. I have made a new release of ESMA_env [v2.0.2](https://github.com/GEOS-ESM/ESMA_env/releases/tag/v2.0.2)

**Pull request merged**
