### PR TITLE
Remove GEOSldas version info from CMakeLists.txt

### PR DESCRIPTION
**Pull request by gmao-rreichle**
Addresses #513.  Tentatively removing GEOSldas version info from CMakeLists.txt.

The reason for doing this is **not** the burden of maintaining the GEOSldas version info in CMakeLists.txt (although we missed updating the version entry for v17.10.0).  

Rather, the concern is that even if the GEOSldas version info is maintained properly in CMakeLists.txt, in many cases the version info would at best provide a starting point because it cannot reflect changes that users make to GEOSldas before the build. 

Going forward, it may be possible to assemble version info from git as suggested by @tclune:  https://github.com/GEOS-ESM/GEOSldas/issues/513#issuecomment-1015471164

@biljanaorescanin : When you get a chance, please test the PR to make sure we can get away with not having GEOSldas version info in CMakeLists.txt.  If there is a problem, we can restore the version info, set the version to 0.0.0 (something that's obviously bogus), and try again.  

cc: @mathomp4 @weiyuan-jiang

### CODE REVIEW

**Comment by biljanaorescanin** [comment]
This PR passed all nightly tests.

**Review by biljanaorescanin — APPROVED** [review]

**Review by mathomp4 — APPROVED** [review]
Seems safe!

**Comment by gmao-rreichle** [comment]
Just for the record, after removing the GEOSldas version info from CMakeLists.txt in this PR, the GEOSldas build now issues a warning (see below).  I suspect we could make the warning disappear by adding a dummy version ("0.0.0").  I don't think that's critical but let me know if you'd rather see a dummy version than nothing at all.

```
CMake Warning at @cmake/@ecbuild/cmake/ecbuild_log.cmake:158 (message):
  WARN - Please set a version in the project statement:

         project( GEOSldas VERSION x.x.x LANGUAGES C CXX Fortran )
```

cc: @weiyuan-jiang @tclune @mathomp4 @biljanaorescanin

**Comment by tclune** [comment]
Ideally we could suppress the warning, but I don't immediately see a way to do that.    I'm a bit surprised that _ecbuild_ is where the warning comes from as `project` is a CMake command.

But a version of 0.0.0 is preferable to the warning, IMO.  Still obvious that it is meaningless, but does not create noise in the cmake step.     We already have more warnings there than @mathomp4 and I would like.

**Comment by mathomp4** [comment]
Hmm. Yeah. ecbuild will do that, it looks like. And I'm pretty sure `ecbuild_declare_project()` is required.

Indeed, if we ever update to be based on the mother ecbuild, [I think it is *required*](https://github.com/ecmwf/ecbuild/blob/77ad783236c72e66c449a8b58000b751807c80f3/cmake/ecbuild_declare_project.cmake#L92-L106) as the else path that leads to that `ecbuild_warn` in our ecbuild, is gone and only an `ecbuild_critical` remains.

**Pull request merged**
