### PR TITLE
fix character length

### PR DESCRIPTION
**Pull request by weiyuan-jiang**
Increase the filenames' ( with path) length so the filenames don't get truncated.

### CODE REVIEW

**Review by gmao-rreichle — COMMENTED** [review]
Looks good to me.  Not sure if a formal test was done, or if it's needed.  Could be considered "0-diff trivial", and the build works.  
However, this PR cannot just be merged because this PR has a "conflict" with #569, which moves around some of the utilities that are changed in this PR.  That is, some of the changes here would be lost unless they are also added to #569.  
Merging this PR therefore requires more thought/discussion.

**Comment by weiyuan-jiang** [comment]
I have tested it. It is zero-diff

**Comment by gmao-rreichle** [comment]
I'm hopeful that we can merge #569 very soon.  Let's keep the present PR (#572) on hold for now.  After #569 is merged, I will create a new PR that replicates the present PR on top of (then revised) develop branch.

**Comment by gmao-rreichle** [comment]
Replaced with #574.  Closing.

**Pull request closed without merging**
