### PR TITLE
fix for debug flags

### PR DESCRIPTION
**Pull request by weiyuan-jiang**
A combination of some debug flags leads to an internal writing failure. This is a workaround to address #362

### CODE REVIEW

**Comment by gmao-rreichle** [comment]
@weiyuan-jiang : 
I suggest a revised fix, see commit [443291b](https://github.com/GEOS-ESM/GEOSldas/commit/443291bf19872206ef316645de07a51a67210c42)
Please take a look.  (I did not yet make sure that the fix even compiles.)
I guess the ultimate source of the problem is that subroutine get_io_filename() was called with "option=3" and a "date_time" argument that did not have the pentad field set properly.  BUT, I don't see a call to get_io_filename() with "option=3" anywhere in develop.  Is this something that came up in a developer's new branch?

**Comment by biljanaorescanin** [comment]
@gmao-rreichle I got this error today on not so up to date branch (October clone). But than same error was reproduced with current develop. @weiyuan-jiang  was able to reproduce it as well.

**Review by weiyuan-jiang — COMMENTED** [review]
looks good to me

**Comment by weiyuan-jiang** [comment]
The run didn't exit successfully. Can you post the run time error?

**Comment by biljanaorescanin** [comment]
1:
sacct: error: slurm_persist_conn_open_without_init: failed to open persistent connection to rmdb5:6830: Connection timed out
sacct: error: slurmdbd: Sending PersistInit msg: Connection timed out
sacct: error: Problem talking to the database: Connection timed out

**Comment by biljanaorescanin** [comment]
@gmao-rreichle @weiyuan-jiang  Just by re-running tests now GNUGLOBAL/assim passed. Its was obviously some glitch in post processing. Good news is this PR is zero diff now.

**Review by gmao-rreichle — APPROVED** [review]

**Pull request merged**
