### PR TITLE
Restart by OServer

### PR DESCRIPTION
**Pull request by biljanaorescanin**
Edit the RC_FILE to use WRITE_RESTART_BY_OSERVER: YES

### CODE REVIEW

**Comment by mathomp4** [comment]
Note that I usually only turn this on for Open MPI with the AGCM. I've never seen a need for it with Intel MPI or MPT. The bug/slowdown only seems to be when using Open MPI. 

That said, I'm not sure it hurts with Intel?

**Comment by biljanaorescanin** [comment]
With this change test gnuglobal assim part fails for all landpert_restart comparisons.

**Comment by gmao-rreichle** [comment]
Status update:  This still needs more work by @weiyuan-jiang .   Changed to "draft" PR by adding "contingent" label for now.

**Comment by biljanaorescanin** [comment]
Attempt that didn't work. Closing this PR. Another PR will be created once we are ready.

**Pull request closed without merging**
