### PR TITLE
fix mpi_finalize fail

### PR DESCRIPTION
**Pull request by weiyuan-jiang**
Change ESMA_env and MAPL version

### CODE REVIEW

**Comment by mathomp4** [comment]
Hold please. Matt was an idiot

**Comment by mathomp4** [comment]
Yeah. Matt tagged `v2.1.3` with `v2.1.2+intel19.1`. I created a `v2.1.3+intel19.1` and pushed that tag. It is *identical* to `v2.1.2+intel19.1` I was just being clumsy/stupid.

**Comment by mathomp4** [comment]
Ah. I figured it out. The LDAS never got `v2.1.2` since it was a slight NAS bugfix. LDAS doesn't run at NAS as far as I know, so I never gave you one. So, when I was making this new ESMA_env tag, I saw the last I gave you was 2.1.1 and said, "Let's advance that patch by 1". 

🤞 this is the last time I do this. Sorry about that

**Comment by gmao-rreichle** [comment]
@weiyuan-jiang : Can you please update the branch if needed and then re-test?  I'm a bit lost as to what exactly the tags should be in Externals.cfg.

**Comment by weiyuan-jiang** [comment]
I have updated it and am testing it fully under sles12

**Pull request merged**
