### PR TITLE
updated code to use the Level 2 mwRTM parameters

### PR DESCRIPTION
**Pull request by gmao-qliu**
Addresses changes that are needed to use L-band radiative transfer model (RTM) parameters derived from the SMAP L2 passive retrieval product.

**IMPORTANT:** This PR introduces an **interface change in the runtime configuration parameters (resource variables)** in the `exeinp` file:
```
BCS_PATH:   --> BCS_PATH:  and  BCS_RESOLUTION:
MWRTM_FILE: --> MWRTM_PATH: 
```
That is, `exeinp` files from experiments run with previous releases must be edited to work with the changes from this PR.  Moreover, the `mwrtm_param.nc4` (and, optionally, `vegopacity.bin`) must be provided in a subdirectory `BCS_RESOLUTION:`.

---
Includes all commits from earlier PRs #419, #425, and #426.

### CODE REVIEW

**Review by tclune — APPROVED** [review]
CMake changes good.

**Comment by gmao-rreichle** [comment]
My two most recent commits resolved the merge conflict with develop, fixed minor (no-impact) bugs, and (hopefully) addressed the outstanding issues from PRs #419, #425, and #426 **except** the following:

- [**add VEGOPACITY_FILE to ldas_setup, GEOSldas_LDAS.rc**](https://github.com/GEOS-ESM/GEOSldas/pull/425#issuecomment-880086968)

**Comment by weiyuan-jiang** [comment]
@gmao-rreichle , ldas_setup now can add vegopacity file.  "MWRTM_FILE" in the input script file for ldas_setup should be changed to "MWRTM_PATH" which may contain "mwRTM_param.nc4" and "vegopacity.bin" . @gmao-qliu , would you help to test the ldas_setup?

**Comment by gmao-rreichle** [comment]
Thanks, @weiyuan-jiang.  While you're at it, can you please add the missing "global-to-domain" mapping after reading the veg_opacity from the input file?

**Comment by weiyuan-jiang** [comment]
> Thanks, @weiyuan-jiang. While you're at it, can you please add the missing "global-to-domain" mapping after reading the veg_opacity from the input file?

That should happen automatically after I added the vegopacity file to group here[ ](https://github.com/GEOS-ESM/GEOSldas/blob/a06fcd92d6dd8cd361dc665c36d9a5ece82613e5/src/Applications/LDAS_App/ldas_setup#L731-L732)

**Comment by weiyuan-jiang** [comment]
The link is not shown up in my reply [ ](https://github.com/GEOS-ESM/GEOSldas/blob/a06fcd92d6dd8cd361dc665c36d9a5ece82613e5/src/Applications/LDAS_App/ldas_setup#L731-L732)

**Comment by gmao-rreichle** [comment]
> > Thanks, @weiyuan-jiang. While you're at it, can you please add the missing "global-to-domain" mapping after reading the veg_opacity from the input file?
> 
> That should happen automatically after I added the vegopacity file to group here [(line -731-732)](https://github.com/GEOS-ESM/GEOSldas/blob/a06fcd92d6dd8cd361dc665c36d9a5ece82613e5/src/Applications/LDAS_App/ldas_setup#L731-L732)

Ok.  Sorry I keep being confused about the workings of MAPL.  But the link above ("line 731-732") is for ldas_setup, which only makes sure the vegopacity file can be found by GEOSldas.x.  Since vegopacity is a seasonally varying climatology (just like LAI, and unlike the fields in the mwRTM param file), GEOSldas.x will read it repeatedly.  If I'm not mistaken, the pertinent piece is then the `MAPL` object in [this `MAPL_ReadForcing()` call.](https://github.com/GEOS-ESM/GEOSldas/blob/a06fcd92d6dd8cd361dc665c36d9a5ece82613e5/src/Components/GEOSldas_GridComp/GEOSlandassim_GridComp/GEOS_LandAssimGridComp.F90#L2766).  That is, the `MAPL` object knows which N_catl tiles to extract from the vegopacity file for each local domain.  Does this make any sense?

**Comment by weiyuan-jiang** [comment]
> 

That is not how we deal with the mapping. ldas_setup do the mapping here.  https://github.com/GEOS-ESM/GEOSldas/blob/a06fcd92d6dd8cd361dc665c36d9a5ece82613e5/src/Applications/LDAS_App/ldas_setup#L743-L744  .  GEOSldas.x does not know about the mapping any more.

**Comment by gmao-rreichle** [comment]
Thanks, @weiyuan-jiang.  Now I get it, I think...  Sorry it's taken me so long to refresh my memory.   
In a nutshell, there's a pre-processed  vegopacity file that includes only the tiles for the simulation domain.  MAPL then thinks that this potentially regional simulation domain is the "global" domain. 
This has implications for the ["snow albedo" PR in the GCM GridComp](https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/550) that @biljanaorescanin is working on.  Her current implementation reads a global tile file directly into the Catchment GridComp.  To make this work for GEOSldas, we would have to add the snow albedo file to the list of files that need to be preprocessed.  So rather than changing Biljana's GCM GridComp implementation, we would need a matching GEOSldas PR.  Does this sound right? 
For reference, the snow albedo file is most similar to the mwRTM_param file because it's nc4 and contains a static (time-invariant) parameter.

**Comment by gmao-qliu** [comment]
> @gmao-rreichle , ldas_setup now can add vegopacity file. "MWRTM_FILE" in the input script file for ldas_setup should be changed to "MWRTM_PATH" which may contain "mwRTM_param.nc4" and "vegopacity.bin" . @gmao-qliu , would you help to test the ldas_setup?

I just tested "ldas_setup". It works with both L2RTM and the old RTM setting.

**Comment by gmao-qliu** [comment]
It passed the nightly test before I created the pull-request. @gmao-rreichle @weiyuan-jiang 

Full log file: /discover/nobackup/qliu/SystemTests/logs/LDAS/2022-01-31/log.14:46:11

Runtype	Clone	Build	Build Time	Model Run/Compare	Assim Run/Compare
-------	-----	-----	----------	-----------------	-----------------
conus	pass	pass	13 min	pass/pass	-- / --
global	--	--	--	pass/pass	pass/pass
globalcs	--	--	--	pass/pass	pass/pass
globalcnclm4	--	--	--	pass/pass	-- / --

**Comment by gmao-rreichle** [comment]
> It passed the nightly test before I created the pull-request.

Thanks, @gmao-qliu.  I took another look at the run failures this morning.  @weiyuan-jiang, it's looking like this is a problem with the latest changes to ldas_setup.  When I do setup with this branch for the global assim test case, LDAS.rc contains the following line: 

`MWRTM_FILE:                         /discover/nobackup/mathomp4/LDAS_Restarts/NGHTLY_TST_TV4000/mwRTM_param.nc4`

In the nightly test with develop, LDAS.rc instead contains this line:

`LANDASSIM_INTERNAL_RESTART_FILE:    ../input/restart/mwrtm_param_rst`

When I (i) manually edit LDAS.rc after setup to look like that from the nightly test and (ii) create a link:

`ln -s /discover/nobackup/mathomp4/LDAS_Restarts/NGHTLY_TST_TV4000/mwRTM_param.nc4 [...]/input/restart/mwrtm_param_rst`

then the run failure goes away and I get 0-diff results.  I haven't figured out yet how to change ldas_setup.

**Comment by weiyuan-jiang** [comment]
> > It passed the nightly test before I created the pull-request.
> 
> Thanks, @gmao-qliu. I took another look at the run failures this morning. @weiyuan-jiang, it's looking like this is a problem with the latest changes to ldas_setup. When I do setup with this branch for the global assim test case, LDAS.rc contains the following line:
> 
> `MWRTM_FILE: /discover/nobackup/mathomp4/LDAS_Restarts/NGHTLY_TST_TV4000/mwRTM_param.nc4`
> 
> In the nightly test with develop, LDAS.rc instead contains this line:
> 
> `LANDASSIM_INTERNAL_RESTART_FILE: ../input/restart/mwrtm_param_rst`
> 
> When I (i) manually edit LDAS.rc after setup to look like that from the nightly test and (ii) create a link:
> 
> `ln -s /discover/nobackup/mathomp4/LDAS_Restarts/NGHTLY_TST_TV4000/mwRTM_param.nc4 [...]/input/restart/mwrtm_param_rst`
> 
> then the run failure goes away and I get 0-diff results. I haven't figured out yet how to change ldas_setup.
> 
> PS: Just to confirm, the [commit before the ldas_setup changes](https://github.com/GEOS-ESM/GEOSldas/pull/521/commits/71293d86451b60bfa9f874029a2e58e69b3f07ba) passes the global assim test case.

I am looking into it now...

**Comment by weiyuan-jiang** [comment]
> `MWRTM_FILE: /discover/nobackup/mathomp4/LDAS_Restarts/NGHTLY_TST_TV4000/mwRTM_param.nc4`

What is your version of GEOSldas that has this in the LDAS.rc? I thought we remove it long time ago. Can you show me your test forlder?

**Comment by weiyuan-jiang** [comment]
Oh, the night test should fail because we need to change the input file's "MWRTM_FILE"  to "MWRTM_PATH"

**Comment by weiyuan-jiang** [comment]
> ldas_setup now can add vegopacity file. "MWRTM_FILE" in the input script file for ldas_setup should be changed to "MWRTM_PATH" which may contain "mwRTM_param.nc4" and "vegopacity.bin" . @gmao-qliu , would you help to test the ldas_setup?

@gmao-rreichle @gmao-qliu  above is the information after I commit ldas_setup. I think Qing has test it.

**Comment by gmao-rreichle** [comment]
@weiyuan-jiang:  Yes, the problem is with the config of the LDAS_GLOBAL/assim test case, which does not yet reflect the intentional interface change from `MWRTM_FILE:` to `MWRTM_PATH:`.  It's very obvious after looking at this fresh this morning and with hindsight.  I was too tired and there were too many other things going on when I tried to sort this out on Friday afternoon and evening.  
Having said that, it would be good to adjust ldas_setup so it processes the MWRTM files exactly like the bcs files (see #533).  Would you have time today to take a look?

**Comment by weiyuan-jiang** [comment]
Now the new push change the interface again. The input file should contain BCS_RESOLUTION. It will add to BCS_PATH or MWRTM_PATH to obtain the real paths of the BCS and mwRTM. @gmao-qliu @gmao-rreichle

**Comment by gmao-rreichle** [comment]
The most recent commits improve the documentation and fix no-data-value problems with the new vegopacity export variable. 
 Related to the latter, the `vegopacity.bin` file: 
- **must use MAPL_UNDEF (1.e15) as the no-data-value** (b/c of MAPL_ReadForcing()) and 
- should **not** contain small negative values (around -1.e-10).

I verified that the branch is 0-diff against develop in the nightly LDAS_GLOBAL/assim test (after suitably changing the global.assim.exec file to reflect the interface changes, ie, BCS_PATH, BCS_RESOLUTION, MWRTM_PATH).

I also verified that the branch runs with mwrtm parameters from the SMAP L2_SM_P_E product (mwrtm_param.nc4 and vegopacity.bin) in the configuration of the nightly LDAS_GLOBAL/assim test.  As expected, this run is not 0-diff against develop.

**Review by biljanaorescanin — APPROVED** [review]

**Pull request merged**
