### PR TITLE
Add reader for S2S AODAS forcing and S2S bias-corrected forecast forcing

### PR DESCRIPTION
**Pull request by gmao-jkolassa**
Added reader get_BC_GEOS_hindcast in **LDAS_Forcing.F90** This reader was initially written by Fanwei Zeng and has been adapted by @gmao-jkolassa to (1) account for changes in the handling of netcdf files and (2) to extract the ensemble number and initialization month from the 'met_tag' rather than through separate arguments provided in LDAS.rc.

The met_tag for using these forcing data takes the form 'HindcastBC_netcdf_ensX_MMMDD', where 'ensX' specifies the S2S ensemble member to be used (for example, ens1, ens2, etc.) and 'MMMDD' specifies the initialization date (e.g., jan01). The met_path is '/discover/nobackup/projects/gmao/geos_carb/fzeng/FORECASTS/GEOS5/CLIM/GEOS5v2/BCSD_Final/6-hourly/'. This information has also been added to the documentation in **doc/README.MetForcing_and_BCS.md**

Note for @gmao-rreichle: The code to parse the ensemble member number and the initialization month from the met_tag was only 4 lines long. So instead of writing a new subroutine to parse the met_tag or modify one of the existing parsing subroutines, I opted here to include this parsing in the reader itself. Please let me know if you would like this changed.

cc: @gmao-rreichle @biljanaorescanin @weiyuan-jiang @rdkoster

### CODE REVIEW

**Comment by gmao-rreichle** [comment]
@gmao-jkolassa : 

Thanks for putting the PR together.  I created a new branch ([feature/jkolassa_s2s_forc_reader_RR](https://github.com/GEOS-ESM/GEOSldas/tree/feature/jkolassa_s2s_forc_reader_RR)) with a few simplifications and some cleanup.
The following link shows the differences w.r.t. your branch (and some white space differences suppressed per the "?w=1" string at the end of the URL):
https://github.com/GEOS-ESM/GEOSldas/compare/feature/jkolassa_s2s_forc_reader..feature/jkolassa_s2s_forc_reader_RR?w=1

The changes include the following:
- changed string (name) of met_tag for clarity (also changed subroutine name)
- for consistency, use _double_ underscore to separate parsed elements of met_tag 
- edited comments
- removed everything to do with net shortwave (no longer used)
- removed "save" and "first_ct" to determine 'ensX' and 'init_MMMDD' (more trouble than it's worth)
- removed enforcing non-negative numbers; this is done in repair_forcing(), which already ensures that Qair and Wind are non-negative;  if more resets are needed, they should be put into repair_forcing()
- fixed indentation (which created a bunch of white-space differences)

Please take a look and verify that everything is ok. In particular, please make sure the comments that describe the data are correct.  If the changes on my branch are ok, please merge them into your branch (which will then automatically update the PR).

A few more things to consider:
- I suppose 'ensX' with a single-digit ensemble ID is a convention that comes from either S2S or the s/w that processes the S2S output into 6-hourly data.  Looking ahead, it might be useful to leave room for numbers greater than 9.  Doesn't have to be done now, but something to think about. 
- I used the string "BiasCorr" in the met_tag, assuming "BC" did indeed imply "BiasCorr" and not "boundary conditions" (the more common use of the abbreviation "bc").   I didn't use "BiasCorr" in the subroutine name because the subroutine has little to do with the bias correction.  It would look exactly the same if there was no bias correction applied to the forcing data, as is the case for Jongmin's AODAS forcing reader.  Once we're agreed on the changes in my branch, it may be useful to take a look at Jongmin's reader and see if there's enough overlap to unify the two readers.  Ultimately, they both read forcing data created by post-processing S2S output using largely the same code.
- Does the reader work for MET_HINTERP=1?  The comments at the top of the subroutine say that nearest-neighbor interpolation is used.  If MET_HINTERP=1 work, we need to adjust the comments.  If MET_HINTERP=1 does not work, we need to either make it work or remove the relevant code. 
- The reader now looks for data from a particular forecast run with a given initial month/day.  Would it be useful to include functionality that always uses, say, 2-month lead forecasts?  This shouldn't be difficult to do by adding another element to the met_tag that can be parsed (eg, `__lead02__`) and processing this information into the desired file name.  This also doesn't have to be done now, just something to think about. 

cc: @jpark50 @rdkoster @biljanaorescanin

**Comment by gmao-jkolassa** [comment]
Made changes to enable both options for met_hinterp in get_GEOSs2sFcst. In order to not have to include the mapping calculations for the interpolation in the reader itself, I had to slightly modify GEOS_openfile to accept two optional input arguments ('lat_str' and 'lon_str'). These are used to indicate that in the bias corrected S2S forcing files, the geolocation variables are called 'latitude' and 'longitude' instead of 'lat' and 'lon'.

Also corrected a minor typo that lead to the initialization month not being read properly from the met_tag.

**Comment by gmao-jkolassa** [comment]
Note: I also removed trailing white spaces while I was making the changes for better readability while I was working. These now all show up as differences and I am not sure how to blend them out. The *relevant* code changes are on lines 2604 - 2885 and 5087 - 5290 of the new LDAS_Forcing.F90.

**Comment by gmao-jkolassa** [comment]
Merged Jongmin's S2S AODAS output reader and my S2S bias-corrected forecast reader into a single reader called get_GEOSs2sFcst.

The respective configurations for using the two forcing datasets are listed below (note the double underscores in the met_tag).

**S2S AODAS:**
MET_TAG: GEOSs2s__AODAS
MET_PATH: /discover/nobackup/jpark50/S2S_Forcing/step4/
FORCE_DTSTEP: 3600

**S2S bias-corrected forecast:**
MET_TAG: GEOSs2s__FcstBiasCorr__ensX__MMMDD
MET_PATH: /discover/nobackup/projects/gmao/geos_carb/fzeng/FORECASTS/GEOS5/CLIM/GEOS5v2/BCSD_Final/6-hourly/
FORCE_DTSTEP: 21600

(with X being the ensemble number and MMMDD being the initialization month and day, see comment above).

**TO DO:**
The documentation for the S2S AODAS data still needs to be added to doc/README.MetForcing_and_BCS.md. @jpark50 , since you know the specifics of these data better than I do, could you please take care of that? Thanks!

**Comment by gmao-rreichle** [comment]
> Note: I also removed trailing white spaces while I was making the changes for better readability while I was working. These now all show up as differences and I am not sure how to blend them out. The _relevant_ code changes are on lines 2604 - 2885 and 5087 - 5290 of the new LDAS_Forcing.F90.

I don't see how the trailing blanks change the readability.  They don't change the indentation.  But they do make it difficult to isolate the differences of interest, even though xxdiff and github.com offer reasonable tools to ignore the differences.  On github.com, white space is ignored by appending `?w=1` to the URL of a difference page.  But this isn't automatic, and because of the excessive number of white space changes, github.com chooses at first to not display any differences at all, which can lead to differences being overlooked.   So unless I'm missing something about readability, I don't think it's helpful to remove the trailing blanks at this time. 

I undid the white space changes in this commit: [1bfbd92](https://github.com/GEOS-ESM/GEOSldas/pull/400/commits/1bfbd92e94a892720c1b2d99e762b487c4c27369)

Note that I also removed a few lines of debugging code and the temporary commenting out of the `write(tmpstring10,*)...` problem.  It looks like this has not yet been resolved.

**Comment by gmao-rreichle** [comment]
@gmao-jkolassa, @jpark50:
I further cleaned up the merged reader:
- The trailing blanks issue was brought into the GEOS S2S reader subroutine with the initial commit.  It should have been cleaned up in this subroutine only, to preserve clean differences with the develop branch in the rest of LDAS_Forcing.F90.  I have now fixed this. 
- I further simplified the MET_TAG and added/revised the documentation.  Please check for accuracy.
- I moved the Fortran "parameter" variables to the top of the subroutine.  It was not good practice to have these in the middle of the if statements. 

I successfully built but did not run.

A couple of questions:
1) The forcing variables are all put into a single file, mixing "states" (e.g., Tair) and "fluxes" (e.g., Precip).  The forcing files do not clearly indicate which variables are flux-type variables and whether they are "backward"- or "forward"-looking.  That is, it's not clear from the file whether the first entry in the FCST file is for 0-6z or for 18z-0z.  At a minimum, a README file needs to accompany the forcing data. Also, the "time_increment" attribute is in seconds but the time variable is in minutes.  This doesn't matter for the reader, but it will throw off utilities that process nc files. 
2) For FCST, the precip variables are "convective (liquid+solid)", "snow", and "total", whereas for AODAS, they are " precipitation variables in the forcing file are "convective liquid", "snow", and "large-scale liquid".  Precip was not handled correctly for AODAS.  I haven't fixed it yet.  Not sure when I'll find the time. 
3) We still need to figure out why we have a problem with `write(tmpstring10,*)...`.  Commenting out the line isn't an option. 



cc: @rdkoster @lcandre2

**Comment by gmao-jkolassa** [comment]
Update: I have put together a README file for the bias-corrected S2S forecast data. It is currently located at /discover/nobackup/jkolassa/S2S_reader_new/README . Please take a look and let me know whether there is anything you would like me to change.

One issue, I do not have write permissions for the forcing data directory (/discover/nobackup/projects/gmao/geos_carb/fzeng/FORECASTS/GEOS5/CLIM/GEOS5v2/BCSD_Final/6-hourly/), so I was unable to move this file there. It seems that Fanwei is still somehow the owner of this directory.

**Comment by gmao-jkolassa** [comment]
Updated reader to compute precipitation components from the total precipitation and the air temperature. If the air temperature is above freezing all precipitation is assigned to the liquid precipitation component, if the temperature is below freezing all precipitation is designated as snowfall. All liquid precipitation is currently designated as large scale rainfall with no convective rainfall. This works for now, because the large scale and convective component are added before they are used to force the land model, but this may need to be modified for other applications and/or future model version.

I also updated the variable names for the AODAS forcing data to match those of the S2S system.

Updates have been tested for GEOSs2sFCST and Jongmin is in the process of running a test for GEOSs2sAODAS.

**Comment by gmao-jkolassa** [comment]
For documentation purposes: While investigating the processing of the S2S_FCST files, Jongmin discovered a time mismatch between the daily S2S output files (defined for 21z to 21z) and the daily MERRA-2 files (defined for 0z to 0z) used to temporally disaggregate the S2S data. It was decided that the resulting uncertainty can be accepted, but users should be aware of this when using the S2S_FCST data.

**Comment by jpark50** [comment]
Updates have been also tested with the GEOSs2sAODAS and it run successfully

**Comment by gmao-jkolassa** [comment]
Also updated the README file with Rolf's comments and a note about the time discrepancy between the daily MERRA-2 and S2S files.

**Comment by gmao-rreichle** [comment]
@gmao-jkolassa, @jpark50:
I added a couple more changes to the reader, see this commit: [e7d7335](https://github.com/GEOS-ESM/GEOSldas/pull/400/commits/e7d7335a5aaed8b94bcc6fbbc4e52040ac5e2b84?w=1) (_note the suppression of white space differences encoded in this link_)
One key change is the AODAS variable name from LWGAB to LWS for consistency with the S2S file specs, which I thought we had agreed on.  This should necessitate a matching change in the AODAS forcing processor. 
The other key change is the added no-data-value detection for total precip in the solid/liquid breakdown.  I don't think this had been done cleanly. 
Also, moving the solid/liquid breakdown to the end of the subroutine saves one if statement within the long do loop through the tiles.  If statements within do loops slow down execution. 
Please take a look and make sure I didn't break anything. 
cc: @lcandre2, @rdkoster

**Comment by gmao-jkolassa** [comment]
Tested for GEOSs2sFCST and reader still works fine.

**Comment by jpark50** [comment]
Tested for GEOSs2sAODAS and reader still works fine.

**Review by gmao-rreichle — APPROVED** [review]
I'm conditionally approving the PR, subject to a final successful 0-diff test.  
@biljanaorescanin, please test using the usual "nightly" suite and, if successful, merge the PR.

**Comment by biljanaorescanin** [comment]
@gmao-rreichle  Ok, running tests now.

**Comment by gmao-jkolassa** [comment]
Performing one last global test before merge.

**Comment by biljanaorescanin** [comment]
> Performing one last global test before merge.

I will wait for your update before any action.

**Comment by biljanaorescanin** [comment]
All tests passed for this PR. @gmao-jkolassa confirmed global run was successful.

**Pull request merged**
