### PR TITLE
adapt to new bcs structure

### PR DESCRIPTION
**Pull request by weiyuan-jiang**
For this PR, the input file's BCS_PATH should just include the bc version like:

1) BCS_PATH:  /discover/nobackup/projects/gmao/bcs_shared/fvInput/ExtData/esm/tiles/NL3/
2) And the resolution should not have  prefix 'SMAP_' (Issue #673 )
3) Needs GEOS_Util's  https://github.com/GEOS-ESM/GEOS_Util/pull/43

@mathomp4 : A heads-up, we will need to update the GEOSldas nightly tests after merging this PR to accommodate the new bcs dir structure.

### CODE REVIEW

**Comment by biljanaorescanin** [comment]
With GEOS_Util branch `feature/wjiang/command_line` and two more changes in input files all nightly tests passed. 
Changes needed in the input files of the Nightly Tests:
1.   `BCS_PATH` has to be updated in all `*.exec` scripts to new layout path.
2.  For assim tests we need to change directory name where we search for `mwrtm_path`. 
     We need to drop `SMAP` from `SMAP_EASEv2_M09`
 (`*/LDAS_Restarts/NGHTLY_TST_TV4000/SMAP_EASEv2_M09` needs to become `*/LDAS_Restarts/NGHTLY_TST_TV4000/EASEv2_M09`)

**Comment by weiyuan-jiang** [comment]
> With GEOS_Util branch `feature/wjiang/command_line` and two more changes in input files all nightly tests passed. Changes needed in the input files of the Nightly Tests:
> 
> 1. `BCS_PATH` has to be updated in all `*.exec` scripts to new layout path.
> 2. For assim tests we need to change directory name where we search for `mwrtm_path`.
>    We need to drop `SMAP` from `SMAP_EASEv2_M09`
>    (`*/LDAS_Restarts/NGHTLY_TST_TV4000/SMAP_EASEv2_M09` needs to become `*/LDAS_Restarts/NGHTLY_TST_TV4000/EASEv2_M09`)

Is mwRTM_param.nc4 file included in BCS ?

**Comment by biljanaorescanin** [comment]
> > With GEOS_Util branch `feature/wjiang/command_line` and two more changes in input files all nightly tests passed. Changes needed in the input files of the Nightly Tests:
> > 
> > 1. `BCS_PATH` has to be updated in all `*.exec` scripts to new layout path.
> > 2. For assim tests we need to change directory name where we search for `mwrtm_path`.
> >    We need to drop `SMAP` from `SMAP_EASEv2_M09`
> >    (`*/LDAS_Restarts/NGHTLY_TST_TV4000/SMAP_EASEv2_M09` needs to become `*/LDAS_Restarts/NGHTLY_TST_TV4000/EASEv2_M09`)
> 
> Is mwRTM_param.nc4 file included in BCS ?

Nope, it is in area I gave path to in upper comment. Currently its here: `*/LDAS_Restarts/NGHTLY_TST_TV4000/SMAP_EASEv2_M09/mwRTM_param.nc4`

**Comment by weiyuan-jiang** [comment]
This PR should work with this GEOS_Util [branch](https://github.com/GEOS-ESM/GEOS_Util/blob/feature/wjiang/add_ease_grid/pre/remap_restart/remap_questions.py)

**Comment by gmao-rreichle** [comment]
> This has to change we get error because SLES15 has nco/5.1.7 , due to error `landpert` files are not done
> 
> https://github.com/GEOS-ESM/GEOSldas/blob/e1f83489db2d5f01c45af3f066fca345667712ac/src/Applications/LDAS_App/lenkf.j.template#L71-L76

I think the conditional `if ( -e /etc/os-release ) then` was introduced when Discover transitioned to SLES11.   Going forward, don't we need something like (csh syntax):

```
set OS_VERSION=`grep VERSION_ID /etc/os-release | cut -d= -f2 | cut -d. -f1 | sed 's/"//g'`
if ($OS_VERSION == 15) then
  ...
```

We'll also need to figure out what this should do when we're not on Discover.

**Review by gmao-rreichle — APPROVED** [review]

**Pull request merged**
