### PR TITLE
Make GEOSldas work for SLES15 / Milan

### PR DESCRIPTION
**Pull request by weiyuan-jiang**
Address issue #691 and added support for SLES15

### CODE REVIEW

**Comment by biljanaorescanin** [comment]
All Nightly Tests passed on SLES-12. 
I was able to run few day experiment on SLES-15.
If we wish to run Nightly Tests on SLES-15 some changes are still needed.

**Comment by gmao-rreichle** [comment]
@biljanaorescanin ran the Nightly Tests on SLES15 and reports only roundoff differences.  (The CNCLM45 test fails to run on GNU because of a floating point exception, which is addressed here:  https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/898.)

I further verified that @biljanaorescanin's LDAS_GLOBAL/assim test on SLES-15 has only roundoff differences based on my usual plots of the brightness temperature O-Fs and A-Fs.

**Review by gmao-rreichle — APPROVED** [review]

**Comment by gmao-rreichle** [comment]
@GEOS-ESM/cmake-team : Can you please approve this PR or let us know what might need changing?  Thanks!

**Comment by mathomp4** [comment]
> @GEOS-ESM/cmake-team : Can you please approve this PR or let us know what might need changing? Thanks!

@gmao-rreichle We can't approve until it is no longer draft. But the Cmake looks fine to me.

**Pull request merged**
