### PR TITLE
Change Z0_FORM to 4, use INLv3

### PR DESCRIPTION
**Pull request by JustinPerket**
wait to merge until ready to change baseline.

@mathomp4, this will go with changing exec files for nightly test. I can provide the changes

### CODE REVIEW

**Comment by JustinPerket** [comment]
> I hope my minor fixes are ok.

yup, looks good!

**Comment by JustinPerket** [comment]
@GEOS-ESM/ldas-gatekeepers, requires another approval since I had to manually merge from develop

**Comment by JustinPerket** [comment]
Merging. The code changes will be 0diff in the nightly test, but not when running ldas_setup to generate new exec file.

This folder has modified exec files for @mathomp4 to run the nightly test:

        /home/jperket/SI_Team/scripts/systest/input/LDAS-update20191210

**Comment by mathomp4** [comment]
@gmao-rreichle @JustinPerket I've copied over the `.exec` files into my nightly test inputs. Let me know if I should not have done that. (And, yes, it seem non-zero diff to the BASELINE)

**Comment by JustinPerket** [comment]
I think we're ready for that. @gmao-rreichle can contradict me when he's free from AGU activities if not.

**Comment by gmao-rreichle** [comment]
ok with me to make the change in the nightly tests, 
but I will not be able to verify the nightly tests tomorrow - too busy at AGU.
this means the test would fail for a few days until I'm back in the office and caught up, hopefully early next week.
- rolf

-----------------------------------------------------------------
 Rolf Reichle
 NASA Goddard Space Flight Center, Code 610.1
 Greenbelt Road, Greenbelt, MD 20771, USA
 Tel. +1-301-614-5693
 http://gmao.gsfc.nasa.gov/GMAO_personnel/Reichle_Rolf
 http://science.gsfc.nasa.gov/sed/bio/rolf.h.reichle
-----------------------------------------------------------------


________________________________________

**Pull request merged**
