### PR TITLE
allow processors without tiles (N_catl=0) 

### PR DESCRIPTION
**Pull request by weiyuan-jiang**
If a process has no tile,  it crashes when running data assimilation.  Is it safe to assume  N_obsl = 0 if N_catl =0 ? @gmao-rreichle

### CODE REVIEW

**Comment by gmao-rreichle** [comment]
@weiyuan-jiang : I added a few changes, see commit message [f7fdb61](https://github.com/GEOS-ESM/GEOSldas/pull/309/commits/f7fdb610f1c6656e286c30a59dfb14f99359715f)

I did not test (or even compile) the changes. Please review and let me know if you have any questions.

> Is it safe to assume N_obsl = 0 if N_catl =0 ?

That should be safe.  If there are no tiles on a given processor, then there cannot be obs assigned to tiles on that processor.

**Comment by gmao-rreichle** [comment]
@weiyuan-jiang : I agree with the change of "obsbias_ok" to "obsbias_ok_tmp" late in subroutine get_obs_pred().
I reverted to the original code for handling the optional argument "obsbias_ok" (ie, I removed the "Nobs_l>0" condition.
The condition would also apply to the processing of the subsequent optional argument ("fcsterr_inflation_fac"), and probably many other statements throughout the subroutine.  At this time, I think it's best to apply the "Nobs_l>0" (or equivalent) condition only where it is necessary to avoid giving the impression that the condition was applied consistently throughout the subroutine.
I went ahead and re-approved the pull request.  As far as I am concerned, it is ready for merging.

@biljanaorescanin

**Review by gmao-rreichle — DISMISSED** [review]

**Comment by weiyuan-jiang** [comment]
If N_obsl =0, the assignment obsbias_ok_tmp = .false.  will crash.  @gmao-rreichle

**Comment by gmao-rreichle** [comment]
Of course, sorry!  Thanks for catching this, @weiyuan-jiang 
I re-instated the condition "N_obsl>0".
Should now be good to go.  Or so I hope...

**Review by gmao-rreichle — APPROVED** [review]

**Comment by gmao-rreichle** [comment]
Successful 0-diff tests by @biljanaorescanin completed 16 Sep 2020.

**Pull request merged**
