### PR TITLE
fix for max(xhalo, ...)

### PR DESCRIPTION
**Pull request by weiyuan-jiang**
The intrinsic function "max" needs the arguments with the same shape ( except the scalar).

### CODE REVIEW

**Comment by gmao-rreichle** [comment]
I've been staring at the revisions for a while... I'm nervous that it's rather risky to assig a distance of 0. in subroutine `dist_km2deg()` when the input is a no-data-value.  This works for the use case in question, where we take a `max()` of what comes back from `dist_km2deg()`.  But what if `dist_km2deg()` is used in a way that is not followed by a `max()` operation?

From the description above I'm guessing that the offending line is the following: 

` xhalo = max( xhalo, tmprx(1:kk) ) `

Specifically, I understand that the problem in the statement above is that `xhalo` is a scalar and `tmprx(1:kk)` is a vector.  

Could we just replace the above line with the following:

`xhalo = max( xhalo,  maxval( tmprx(1:kk) ) )` 

Maybe that's a simpler way to achieve the same result, without the risky modification to `dist_km2deg()`.

**Comment by weiyuan-jiang** [comment]
Xhalo is a vector. That is the source of the problem. We can assign nodata to dist_km2deg if the input is nodata.

**Comment by weiyuan-jiang** [comment]
I am wondering if the dist_km2deg works for lat-lon grid

**Comment by weiyuan-jiang** [comment]
closed.  it is addressed by #316

**Pull request closed without merging**
